from enum import Enum


class BalanceSheetItem(str, Enum):
    ACCOUNTS_PAYABLES = "Accounts_Payables"
    ACCOUNTS_RECEIVABLES = "Accounts_Receivables"
    ACCRUED_EXPENSES = "Accrued_Expenses"
    ACCUMULATED_OTHER_COMPREHENSIVE_INCOME_LOSS = "Accumulated_Other_Comprehensive_Income_Loss"
    ADDITIONAL_PAID_IN_CAPITAL = "Additional_Paid_In_Capital"
    CAPITAL_LEASE_OBLIGATIONS = "Capital_Lease_Obligations"
    CAPITAL_LEASE_OBLIGATIONS_CURRENT = "Capital_Lease_Obligations_Current"
    CAPITAL_LEASE_OBLIGATIONS_NON_CURRENT = "Capital_Lease_Obligations_Non_Current"
    CASH_AND_CASH_EQUIVALENTS = "Cash_And_Cash_Equivalents"
    CASH_AND_SHORT_TERM_INVESTMENTS = "Cash_And_Short_Term_Investments"
    COMMON_STOCK = "Common_Stock"
    DEFERRED_REVENUE = "Deferred_Revenue"
    DEFERRED_REVENUE_NON_CURRENT = "Deferred_Revenue_Non_Current"
    DEFERRED_TAX_LIABILITIES_NON_CURRENT = "Deferred_Tax_Liabilities_Non_Current"
    GOODWILL = "Goodwill"
    GOODWILL_AND_INTANGIBLE_ASSETS = "Goodwill_And_Intangible_Assets"
    INTANGIBLE_ASSETS = "Intangible_Assets"
    INVENTORY = "Inventory"
    LONG_TERM_DEBT = "Long_Term_Debt"
    LONG_TERM_INVESTMENTS = "Long_Term_Investments"
    MINORITY_INTEREST = "Minority_Interest"
    NET_DEBT = "Net_Debt"
    NET_RECEIVABLES = "Net_Receivables"
    OTHER_ASSETS = "Other_Assets"
    OTHER_CURRENT_ASSETS = "Other_Current_Assets"
    OTHER_CURRENT_LIABILITIES = "Other_Current_Liabilities"
    OTHER_LIABILITIES = "Other_Liabilities"
    OTHER_NON_CURRENT_ASSETS = "Other_Non_Current_Assets"
    OTHER_NON_CURRENT_LIABILITIES = "Other_Non_Current_Liabilities"
    OTHER_PAYABLES = "Other_Payables"
    OTHER_RECEIVABLES = "Other_Receivables"
    OTHER_TOTAL_STOCKHOLDERS_EQUITY = "Other_Total_Stockholders_Equity"
    PREFERRED_STOCK = "Preferred_Stock"
    PREPAIDS = "Prepaids"
    PROPERTY_PLANT_EQUIPMENT_NET = "Property_Plant_Equipment_Net"
    RETAINED_EARNINGS = "Retained_Earnings"
    SHORT_TERM_DEBT = "Short_Term_Debt"
    SHORT_TERM_INVESTMENTS = "Short_Term_Investments"
    TAX_ASSETS = "Tax_Assets"
    TAX_PAYABLES = "Tax_Payables"
    TOTAL_ASSETS = "Total_Assets"
    TOTAL_CURRENT_ASSETS = "Total_Current_Assets"
    TOTAL_CURRENT_LIABILITIES = "Total_Current_Liabilities"
    TOTAL_DEBT = "Total_Debt"
    TOTAL_EQUITY = "Total_Equity"
    TOTAL_INVESTMENTS = "Total_Investments"
    TOTAL_LIABILITIES = "Total_Liabilities"
    TOTAL_LIABILITIES_AND_TOTAL_EQUITY = "Total_Liabilities_And_Total_Equity"
    TOTAL_NON_CURRENT_ASSETS = "Total_Non_Current_Assets"
    TOTAL_NON_CURRENT_LIABILITIES = "Total_Non_Current_Liabilities"
    TOTAL_PAYABLES = "Total_Payables"
    TOTAL_STOCKHOLDERS_EQUITY = "Total_Stockholders_Equity"
    TREASURY_STOCK = "Treasury_Stock"

    def __str__(self) -> str:
        return str(self.value)
