from enum import Enum


class CashFlowItem(str, Enum):
    ACCOUNTS_PAYABLES = "Accounts_Payables"
    ACCOUNTS_RECEIVABLES = "Accounts_Receivables"
    ACQUISITIONS_NET = "Acquisitions_Net"
    CAPITAL_EXPENDITURE = "Capital_Expenditure"
    CASH_AT_BEGINNING_OF_PERIOD = "Cash_At_Beginning_Of_Period"
    CASH_AT_END_OF_PERIOD = "Cash_At_End_Of_Period"
    CHANGE_IN_WORKING_CAPITAL = "Change_In_Working_Capital"
    COMMON_DIVIDENDS_PAID = "Common_Dividends_Paid"
    COMMON_STOCK_ISSUANCE = "Common_Stock_Issuance"
    COMMON_STOCK_REPURCHASED = "Common_Stock_Repurchased"
    DEFERRED_INCOME_TAX = "Deferred_Income_Tax"
    DEPRECIATION_AND_AMORTIZATION = "Depreciation_And_Amortization"
    EFFECT_OF_FOREX_CHANGES_ON_CASH = "Effect_Of_Forex_Changes_On_Cash"
    FREE_CASH_FLOW = "Free_Cash_Flow"
    INCOME_TAXES_PAID = "Income_Taxes_Paid"
    INTEREST_PAID = "Interest_Paid"
    INVENTORY = "Inventory"
    INVESTMENTS_IN_PROPERTY_PLANT_AND_EQUIPMENT = "Investments_In_Property_Plant_And_Equipment"
    LONG_TERM_NET_DEBT_ISSUANCE = "Long_Term_Net_Debt_Issuance"
    NET_CASH_PROVIDED_BY_FINANCING_ACTIVITIES = "Net_Cash_Provided_By_Financing_Activities"
    NET_CASH_PROVIDED_BY_INVESTING_ACTIVITIES = "Net_Cash_Provided_By_Investing_Activities"
    NET_CASH_PROVIDED_BY_OPERATING_ACTIVITIES = "Net_Cash_Provided_By_Operating_Activities"
    NET_CHANGE_IN_CASH = "Net_Change_In_Cash"
    NET_COMMON_STOCK_ISSUANCE = "Net_Common_Stock_Issuance"
    NET_DEBT_ISSUANCE = "Net_Debt_Issuance"
    NET_DIVIDENDS_PAID = "Net_Dividends_Paid"
    NET_INCOME = "Net_Income"
    NET_PREFERRED_STOCK_ISSUANCE = "Net_Preferred_Stock_Issuance"
    NET_STOCK_ISSUANCE = "Net_Stock_Issuance"
    OPERATING_CASH_FLOW = "Operating_Cash_Flow"
    OTHER_FINANCING_ACTIVITIES = "Other_Financing_Activities"
    OTHER_INVESTING_ACTIVITIES = "Other_Investing_Activities"
    OTHER_NON_CASH_ITEMS = "Other_Non_Cash_Items"
    OTHER_WORKING_CAPITAL = "Other_Working_Capital"
    PREFERRED_DIVIDENDS_PAID = "Preferred_Dividends_Paid"
    PURCHASES_OF_INVESTMENTS = "Purchases_Of_Investments"
    SALES_MATURITIES_OF_INVESTMENTS = "Sales_Maturities_Of_Investments"
    SHORT_TERM_NET_DEBT_ISSUANCE = "Short_Term_Net_Debt_Issuance"
    STOCK_BASED_COMPENSATION = "Stock_Based_Compensation"

    def __str__(self) -> str:
        return str(self.value)
